function resume(){var O='bootstrap',P='begin',Q='gwt.codesvr.resume=',R='gwt.codesvr=',S='resume',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='resume::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='resume.nocache.js',Ib='base',Jb='//',Kb='mgwt.density',Lb='mid',Mb=1.5,Nb='xhigh',Ob='high',Pb=2,Qb='mgwt.formfactor',Rb='formfactor',Sb='&',Tb='iphone',Ub='ipod',Vb='phone',Wb='ipad',Xb='tablet',Yb='android',Zb='mobile',$b='desktop',_b='user.agent',ac='webkit',bc='safari',cc='msie',dc=10,ec=11,fc='ie10',gc=9,hc='ie9',ic=8,jc='ie8',kc='gecko',lc='gecko1_8',mc=3,nc=4,oc='selectingPermutation',pc='resume.devmode.js',qc='3A47C59A11755B3F795C816B08C33D92',rc=':1',sc=':10',tc=':11',uc=':12',vc=':13',wc=':14',xc=':15',yc=':16',zc=':17',Ac=':2',Bc=':3',Cc=':4',Dc=':5',Ec=':6',Fc=':7',Gc=':8',Hc=':9',Ic=':',Jc='.cache.js',Kc='loadExternalRefs',Lc='end',Mc='http:',Nc='file:',Oc='_gwt_dummy_',Pc='__gwtDevModeHook:resume',Qc='Ignoring non-whitelisted Dev Mode URL: ',Rc=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
resume.__sendStats=r;resume.__moduleName=S;resume.__errFn=null;resume.__moduleBase=U;resume.__softPermutationId=V;resume.__computePropValue=null;resume.__getPropMap=null;resume.__installRunAsyncCode=function(){};resume.__gwtStartLoadingFragment=function(){return null};resume.__gwt_isKnownPropertyValue=function(){return false};resume.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};resume.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[resume.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
resume.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(resume.__errFn){n.onerror=function(){resume.__errFn(S,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
resume.__startLoadingFragment=function(a){return D(a)};resume.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,bb);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;resume.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return resume.__moduleBase+a}
function F(){var g=[];var h=V;function i(a,b){var c=g;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var j=[];var k=[];function l(a){var b=k[a](),c=j[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
k[Kb]=function(){if(!window.devicePixelRatio){return Lb}if(window.devicePixelRatio>Mb){return Nb}else if(window.devicePixelRatio>W){return Ob}return Lb};j[Kb]={'high':V,'mid':W,'xhigh':Pb};k[Qb]=function(){var a=location.search;var b=a.indexOf(Rb);if(b>=V){var c=a.substring(b);var d=c.indexOf(vb)+W;var e=c.indexOf(Sb);if(e==-1){e=c.length}return c.substring(d,e)}var f=navigator.userAgent.toLowerCase();if(f.indexOf(Tb)!=-1||f.indexOf(Ub)!=-1){return Vb}else if(f.indexOf(Wb)!=-1){return Xb}else if(f.indexOf(Yb)!=-1){if(f.indexOf(Zb)!=-1){return Vb}else{return Xb}}return $b};j[Qb]={'desktop':V,'phone':W,'tablet':Pb};k[_b]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(ac)!=-1}())return bc;if(function(){return a.indexOf(cc)!=-1&&(b>=dc&&b<ec)}())return fc;if(function(){return a.indexOf(cc)!=-1&&(b>=gc&&b<ec)}())return hc;if(function(){return a.indexOf(cc)!=-1&&(b>=ic&&b<ec)}())return jc;if(function(){return a.indexOf(kc)!=-1||b>=ec}())return lc;return bb};j[_b]={'gecko1_8':V,'ie10':W,'ie8':Pb,'ie9':mc,'safari':nc};__gwt_isKnownPropertyValue=function(a,b){return b in j[a]};resume.__getPropMap=function(){var a={};for(var b in j){if(j.hasOwnProperty(b)){a[b]=l(b)}}return a};resume.__computePropValue=l;o.__gwt_activeModules[S].bindings=resume.__getPropMap;r(O,oc);if(q()){return D(pc)}var m;try{i([Ob,$b,lc],qc);i([Ob,$b,bc],qc+rc);i([Lb,Xb,lc],qc+sc);i([Lb,Xb,bc],qc+tc);i([Nb,$b,lc],qc+uc);i([Nb,$b,bc],qc+vc);i([Nb,Vb,lc],qc+wc);i([Nb,Vb,bc],qc+xc);i([Nb,Xb,lc],qc+yc);i([Nb,Xb,bc],qc+zc);i([Ob,Vb,lc],qc+Ac);i([Ob,Vb,bc],qc+Bc);i([Ob,Xb,lc],qc+Cc);i([Ob,Xb,bc],qc+Dc);i([Lb,$b,lc],qc+Ec);i([Lb,$b,bc],qc+Fc);i([Lb,Vb,lc],qc+Gc);i([Lb,Vb,bc],qc+Hc);m=g[l(Kb)][l(Qb)][l(_b)];var n=m.indexOf(Ic);if(n!=-1){h=parseInt(m.substring(n+W),dc);m=m.substring(V,n)}}catch(a){}resume.__softPermutationId=h;return D(m+Jc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Kc,P);r(Kc,Lc)}
B();resume.__moduleBase=C();t[S].moduleBase=resume.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==Mc||o.location.protocol==Nc);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=Oc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=Pc;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(Qc+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+Rc]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,Lc);A(H);return true}
resume.succeeded=resume();