function resume(){var O='bootstrap',P='begin',Q='gwt.codesvr.resume=',R='gwt.codesvr=',S='resume',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='position:absolute; width:0; height:0; border:none; left: -1000px;',Z=' top: -1000px;',$='CSS1Compat',_='<!doctype html>',ab='',bb='<html><head><\/head><body><\/body><\/html>',cb='undefined',db='readystatechange',eb=10,fb='Chrome',gb='eval("',hb='");',ib='script',jb='javascript',kb='moduleStartup',lb='moduleRequested',mb='Failed to load ',nb='head',ob='meta',pb='name',qb='resume::',rb='::',sb='gwt:property',tb='content',ub='=',vb='gwt:onPropertyErrorFn',wb='Bad handler "',xb='" for "gwt:onPropertyErrorFn"',yb='gwt:onLoadErrorFn',zb='" for "gwt:onLoadErrorFn"',Ab='#',Bb='?',Cb='/',Db='img',Eb='clear.cache.gif',Fb='baseUrl',Gb='resume.nocache.js',Hb='base',Ib='//',Jb='mgwt.density',Kb='mid',Lb=1.5,Mb='xhigh',Nb='high',Ob=2,Pb='mgwt.formfactor',Qb='formfactor',Rb='&',Sb='iphone',Tb='ipod',Ub='phone',Vb='ipad',Wb='tablet',Xb='android',Yb='mobile',Zb='desktop',$b='user.agent',_b='webkit',ac='safari',bc='msie',cc=11,dc='ie10',ec=9,fc='ie9',gc=8,hc='ie8',ic='gecko',jc='gecko1_8',kc=3,lc=4,mc='selectingPermutation',nc='resume.devmode.js',oc='CA8E4DA0C0709C74C0C1F3F93582F641',pc=':1',qc=':10',rc=':11',sc=':12',tc=':13',uc=':14',vc=':15',wc=':16',xc=':17',yc=':2',zc=':3',Ac=':4',Bc=':5',Cc=':6',Dc=':7',Ec=':8',Fc=':9',Gc=':',Hc='.cache.js',Ic='loadExternalRefs',Jc='end',Kc='http:',Lc='file:',Mc='_gwt_dummy_',Nc='__gwtDevModeHook:resume',Oc='Ignoring non-whitelisted Dev Mode URL: ',Pc=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
resume.__sendStats=r;resume.__moduleName=S;resume.__errFn=null;resume.__moduleBase=U;resume.__softPermutationId=V;resume.__computePropValue=null;resume.__getPropMap=null;resume.__installRunAsyncCode=function(){};resume.__gwtStartLoadingFragment=function(){return null};resume.__gwt_isKnownPropertyValue=function(){return false};resume.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};resume.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[resume.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.id=S;a.style.cssText=Y+Z;a.tabIndex=-1;p.body.appendChild(a);u=a.contentWindow.document;u.open();var b=document.compatMode==$?_:ab;u.write(b+bb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==cb){return typeof p.body!=cb&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(p.removeEventListener){p.removeEventListener(db,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(db,d,false)}var e=setInterval(function(){d()},eb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(fb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(gb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(hb));g=e.createElement(ib);g.language=jb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(ib);g.language=jb;g.text=c[i];f.appendChild(g);d(f,g)}}}
resume.onScriptDownloaded=function(a){l(function(){m(a)})};r(kb,lb);var n=p.createElement(ib);n.src=k;if(resume.__errFn){n.onerror=function(){resume.__errFn(S,new Error(mb+code))}}p.getElementsByTagName(nb)[V].appendChild(n)}
resume.__startLoadingFragment=function(a){return D(a)};resume.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(ib);d.language=jb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(ob);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(pb),k;if(j){j=j.replace(qb,ab);if(j.indexOf(rb)>=V){continue}if(j==sb){k=i.getAttribute(tb);if(k){var l,m=k.indexOf(ub);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=ab}c[j]=l}}else if(j==vb){k=i.getAttribute(tb);if(k){try{d=eval(k)}catch(a){alert(wb+k+xb)}}}else if(j==yb){k=i.getAttribute(tb);if(k){try{e=eval(k)}catch(a){alert(wb+k+zb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;resume.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Ab);if(b==-1){b=a.length}var c=a.indexOf(Bb);if(c==-1){c=a.length}var d=a.lastIndexOf(Cb,Math.min(c,b));return d>=V?a.substring(V,d+W):ab}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Db);b.src=a+Eb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Fb);if(a!=null){return a}return ab}
function h(){var a=p.getElementsByTagName(ib);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Gb)!=-1){return e(a[b].src)}}return ab}
function i(){var a=p.getElementsByTagName(Hb);if(a.length>V){return a[a.length-W].href}return ab}
function j(){var a=p.location;return a.href==a.protocol+Ib+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==ab){k=h()}if(k==ab){k=i()}if(k==ab&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return resume.__moduleBase+a}
function F(){var g=[];var h=V;function i(a,b){var c=g;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var j=[];var k=[];function l(a){var b=k[a](),c=j[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
k[Jb]=function(){if(!window.devicePixelRatio){return Kb}if(window.devicePixelRatio>Lb){return Mb}else if(window.devicePixelRatio>W){return Nb}return Kb};j[Jb]={'high':V,'mid':W,'xhigh':Ob};k[Pb]=function(){var a=location.search;var b=a.indexOf(Qb);if(b>=V){var c=a.substring(b);var d=c.indexOf(ub)+W;var e=c.indexOf(Rb);if(e==-1){e=c.length}return c.substring(d,e)}var f=navigator.userAgent.toLowerCase();if(f.indexOf(Sb)!=-1||f.indexOf(Tb)!=-1){return Ub}else if(f.indexOf(Vb)!=-1){return Wb}else if(f.indexOf(Xb)!=-1){if(f.indexOf(Yb)!=-1){return Ub}else{return Wb}}return Zb};j[Pb]={'desktop':V,'phone':W,'tablet':Ob};k[$b]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(_b)!=-1}())return ac;if(function(){return a.indexOf(bc)!=-1&&(b>=eb&&b<cc)}())return dc;if(function(){return a.indexOf(bc)!=-1&&(b>=ec&&b<cc)}())return fc;if(function(){return a.indexOf(bc)!=-1&&(b>=gc&&b<cc)}())return hc;if(function(){return a.indexOf(ic)!=-1||b>=cc}())return jc;return ab};j[$b]={'gecko1_8':V,'ie10':W,'ie8':Ob,'ie9':kc,'safari':lc};__gwt_isKnownPropertyValue=function(a,b){return b in j[a]};resume.__getPropMap=function(){var a={};for(var b in j){if(j.hasOwnProperty(b)){a[b]=l(b)}}return a};resume.__computePropValue=l;o.__gwt_activeModules[S].bindings=resume.__getPropMap;r(O,mc);if(q()){return D(nc)}var m;try{i([Nb,Zb,jc],oc);i([Nb,Zb,ac],oc+pc);i([Kb,Wb,jc],oc+qc);i([Kb,Wb,ac],oc+rc);i([Mb,Zb,jc],oc+sc);i([Mb,Zb,ac],oc+tc);i([Mb,Ub,jc],oc+uc);i([Mb,Ub,ac],oc+vc);i([Mb,Wb,jc],oc+wc);i([Mb,Wb,ac],oc+xc);i([Nb,Ub,jc],oc+yc);i([Nb,Ub,ac],oc+zc);i([Nb,Wb,jc],oc+Ac);i([Nb,Wb,ac],oc+Bc);i([Kb,Zb,jc],oc+Cc);i([Kb,Zb,ac],oc+Dc);i([Kb,Ub,jc],oc+Ec);i([Kb,Ub,ac],oc+Fc);m=g[l(Jb)][l(Pb)][l($b)];var n=m.indexOf(Gc);if(n!=-1){h=parseInt(m.substring(n+W),eb);m=m.substring(V,n)}}catch(a){}resume.__softPermutationId=h;return D(m+Hc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Ic,P);r(Ic,Jc)}
B();resume.__moduleBase=C();t[S].moduleBase=resume.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==Kc||o.location.protocol==Lc);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=Mc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=Nc;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(Oc+L)}L=ab}if(L&&!o[K]){o[K]=true;o[K+Pc]=C();var M=p.createElement(ib);M.src=L;var N=p.getElementsByTagName(nb)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,Jc);A(H);return true}
resume.succeeded=resume();